name: Publish Docker image
on:
  release:
    types: [published]
env:
  DOCKER_REGISTRY: segence
  DOCKER_IMAGE_NAME: ${{ github.event.repository.name }}
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        classifier: [kafka]
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
    - name: Set Versions
      uses: actions/github-script@v7
      id: set_version
      with:
        script: |
          const tag_no_plus = context.ref.replace('+', '')
          core.setOutput('tag_no_plus', tag_no_plus)
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./${{ matrix.classifier }}
        push: true
        tags: ${{steps.set_version.outputs.tag_no_plus}}-${{ matrix.classifier }}
        labels: ${{ steps.meta.outputs.labels }}
